// كتالوج سِمة الابتدائي — نفس عطور الـ Prototype بالعربي والإنجليزي.
// بيُستخدم في وضع العرض (من غير قاعدة بيانات)، وكمان بيتحوّل لـ SQL
// في supabase/seed.sql (npm run gen:seed) عشان يتزرع في قاعدة البيانات.

import type { Category, Coupon, Product, Review } from './types';

const daysAgo = (n: number) =>
  new Date(Date.now() - n * 86_400_000).toISOString();

export const categories: Category[] = [
  {
    id: 'cat_signature',
    slug: 'signature',
    name: 'زجاجات سِمة 100 مل',
    nameEn: 'Signature 100ml Flacons',
    description: 'إكستري وماء عطر بتركيز زيت عالي',
    descriptionEn: 'Extrait and Eau de Parfum with high oil concentration',
    iconKey: 'bottle',
    sortOrder: 1,
  },
  {
    id: 'cat_discovery',
    slug: 'discovery',
    name: 'أطقم العينات',
    nameEn: 'Discovery Sets',
    description: 'جرب في البيت قبل ما تقرر',
    descriptionEn: 'Try at home before you decide',
    iconKey: 'gift',
    sortOrder: 2,
  },
];

const base = {
  brand: 'SIMAT',
  oldPrice: null,
  isActive: true,
  imageUrl: null,
};

export const products: Product[] = [
  {
    ...base,
    id: 'simat-bordeaux',
    slug: 'simat-bordeaux',
    name: 'سِمة بوردو',
    nameEn: 'SIMAT Bordeaux',
    categoryId: 'cat_signature',
    description:
      'ورد طائفي طبيعي مع زعفران دافي وعود معتق. ريحة فخمة تبدأ بورد راقي وتهدى على خشب وعنبر دافي. مناسب جداً للمساء والخروجات الخاصة والأيام الباردة.',
    descriptionEn:
      'Taif rose, warm saffron, and aged agarwood. Rich and warm with a floral opening and a deep woody drydown. Perfect for evenings, dinners, and cooler days.',
    family: 'زهري شرقي وعود معتق',
    familyEn: 'Floral Oriental & Aged Oud',
    kind: 'bottle',
    labelStyle: 'bordeaux',
    price: 3450,
    sizeMl: 100,
    gender: 'unisex',
    concentration: 'parfum',
    topNotes: ['ورد طائفي دمشقي', 'زعفران إيراني', 'حبهان أخضر'],
    heartNotes: ['خشب عود كمبودي معتق', 'أرز الأطلس', 'باتشولي'],
    baseNotes: ['عنبر طبيعي', 'مسك أبيض', 'فانيليا دافية'],
    topNotesEn: ['Taif Damascene Rose', 'Iranian Saffron', 'Green Cardamom'],
    heartNotesEn: ['Aged Cambodian Agarwood', 'Atlas Cedarwood', 'Patchouli'],
    baseNotesEn: ['Natural Amber', 'White Musk', 'Warm Vanilla'],
    longevityHours: 12,
    stock: 40,
    rating: 0,
    ratingCount: 0,
    soldCount: 214,
    isFeatured: true,
    createdAt: daysAgo(60),
  },
  {
    ...base,
    id: 'simat-noir',
    slug: 'simat-noir',
    name: 'سِمة نوار أبسولو',
    nameEn: 'SIMAT Noir Absolu',
    categoryId: 'cat_signature',
    description:
      'عود مدخن مع لمسة جلود فخمة وبخور هادي. عطر تقيل وثابت وله هيبة واضحة، ممتاز للسهرات والمناسبات الرسمية.',
    descriptionEn:
      'Smoky agarwood, noble leather, and clean frankincense. Dark, grounded, and long-lasting. Made for those who like bold, masculine evening fragrances.',
    family: 'أخشاب وجلود مدخنة',
    familyEn: 'Smoky Leather & Heavy Woods',
    kind: 'bottle',
    labelStyle: 'noir',
    price: 4100,
    sizeMl: 100,
    gender: 'men',
    concentration: 'parfum',
    topNotes: ['فلفل أسود', 'لبان حوجري', 'قطران البتولا'],
    heartNotes: ['أخشاب مدخنة', 'جلود ملكية', 'نجيل الهند'],
    baseNotes: ['عود هندي معتق', 'عنبر رمادي', 'خشب الأرز'],
    topNotesEn: ['Black Pepper', 'Cold Frankincense', 'Birch Tar'],
    heartNotesEn: ['Smoked Wood', 'Dark Leather', 'Vetiver'],
    baseNotesEn: ['Indian Agarwood', 'Grey Amber', 'Cedar'],
    longevityHours: 14,
    stock: 25,
    rating: 0,
    ratingCount: 0,
    soldCount: 131,
    isFeatured: true,
    createdAt: daysAgo(45),
  },
  {
    ...base,
    id: 'simat-ivoire',
    slug: 'simat-ivoire',
    name: 'سِمة إيفوار بريفيه',
    nameEn: 'SIMAT Ivoire Privé',
    categoryId: 'cat_signature',
    description:
      'مسك أبيض نظيف مع ياسمين مصري وصندل ناعم. ريحة نظافة وراحة، هادية ومريحة في الاستعمال اليومي والصبح ومناسبات الشغل.',
    descriptionEn:
      'Clean white musk, fresh Nile jasmine, and soft sandalwood. Light, crisp, and comfortable. An easy daily signature that stays close and never overwhelms.',
    family: 'مسك أبيض وزهور نقية',
    familyEn: 'Clean White Musk & Florals',
    kind: 'bottle',
    labelStyle: 'linen',
    price: 3200,
    sizeMl: 100,
    gender: 'women',
    concentration: 'edp',
    topNotes: ['برغموت إيطالي', 'زهر البرتقال', 'فلفل وردي'],
    heartNotes: ['ياسمين وادي النيل', 'خشب صندل ميسور', 'كشمير'],
    baseNotes: ['مسك أبيض نظيف', 'فانيليا بوربون', 'أرز ناعم'],
    topNotesEn: ['Italian Bergamot', 'Orange Blossom', 'Pink Pepper'],
    heartNotesEn: ['Nile Jasmine', 'Mysore Sandalwood', 'Cashmere'],
    baseNotesEn: ['White Musk', 'Bourbon Vanilla', 'Soft Cedar'],
    longevityHours: 9,
    stock: 50,
    rating: 0,
    ratingCount: 0,
    soldCount: 188,
    isFeatured: true,
    createdAt: daysAgo(30),
  },
  {
    ...base,
    id: 'royal-velvet',
    slug: 'royal-velvet',
    name: 'رويال فِلفت',
    nameEn: 'Royal Velvet',
    categoryId: 'cat_signature',
    description:
      'توت أسود غني مع عنبر دافي وخشب البلوط. توليفة مميزة تجمع بين حلاوة خفيفة وعمق دافي، تناسب الجنسين في السهرات.',
    descriptionEn:
      'Ripe dark berries, warm amber, and smoked oakwood. Smooth, slightly sweet, and very distinct. Great for both men and women on evenings out.',
    family: 'عنبر وأخشاب وتوت غني',
    familyEn: 'Ambery Fruity Wood',
    kind: 'bottle',
    labelStyle: 'velvet',
    price: 4850,
    sizeMl: 100,
    gender: 'unisex',
    concentration: 'parfum',
    topNotes: ['توت بري داكن', 'برقوق', 'توابل دافئة'],
    heartNotes: ['ورد دمشقي مخملي', 'خشب البلوط المدخن'],
    baseNotes: ['عنبر ذهبي', 'أخشاب بلسمية', 'مسك ناعم'],
    topNotesEn: ['Dark Berries', 'Wild Plum', 'Warm Spices'],
    heartNotesEn: ['Velvet Damascene Rose', 'Smoked Oakwood'],
    baseNotesEn: ['Golden Amber', 'Balsamic Wood', 'Soft Musk'],
    longevityHours: 12,
    stock: 20,
    rating: 0,
    ratingCount: 0,
    soldCount: 97,
    isFeatured: true,
    createdAt: daysAgo(15),
  },
  {
    ...base,
    id: 'discovery-set',
    slug: 'discovery-set',
    name: 'طقم عينات سِمة (5 × 2 مل)',
    nameEn: 'SIMAT Discovery Set (5 × 2ml)',
    categoryId: 'cat_discovery',
    description:
      'جرب 5 من أكتر عطورنا المحبوبة على جلدك في البيت. ومع العلبة كارت خصم بقيمة 650 ج.م تخصمه من تمن أي زجاجة 100 مل تطلبها بعدين.',
    descriptionEn:
      'Try five of our favorite perfumes at home on your own skin. Inside the box you will find a 650 EGP voucher you can deduct from any 100ml bottle later.',
    family: 'طقم عينات',
    familyEn: 'Discovery Coffret',
    kind: 'set',
    labelStyle: 'noir',
    price: 650,
    sizeMl: 10,
    gender: 'unisex',
    concentration: 'parfum',
    topNotes: ['سِمة بوردو', 'نوار أبسولو', 'إيفوار بريفيه', 'رويال فِلفت', 'دهن عود'],
    heartNotes: [],
    baseNotes: [],
    topNotesEn: ['SIMAT Bordeaux', 'Noir Absolu', 'Ivoire Privé', 'Royal Velvet', 'Dehn Oud'],
    heartNotesEn: [],
    baseNotesEn: [],
    longevityHours: 8,
    stock: 120,
    rating: 0,
    ratingCount: 0,
    soldCount: 402,
    isFeatured: false,
    createdAt: daysAgo(90),
  },
];

export const coupons: Coupon[] = [
  {
    code: 'SIMAT10',
    type: 'percent',
    value: 10,
    minOrder: 0,
    maxDiscount: null,
    expiresAt: daysAgo(-365),
    usageLimit: 0,
    usedCount: 0,
    isActive: true,
  },
  {
    code: 'ALEXANDRIA',
    type: 'percent',
    value: 10,
    minOrder: 0,
    maxDiscount: null,
    expiresAt: daysAgo(-365),
    usageLimit: 0,
    usedCount: 0,
    isActive: true,
  },
  {
    code: 'SIMAT15',
    type: 'percent',
    value: 15,
    minOrder: 3000,
    maxDiscount: null,
    expiresAt: daysAgo(-365),
    usageLimit: 0,
    usedCount: 0,
    isActive: true,
  },
];

/** التقييمات بتتضاف من لوحة التحكم — مفيش تقييمات وهمية في الكتالوج. */
export const reviews: Review[] = [];
