// بيانات المتجر الابتدائية — نفس منتجات التطبيق بالظبط.
// بتُستخدم في وضع العرض (من غير قاعدة بيانات) وكمان بتتحوّل لـ SQL
// في supabase/seed.sql عشان تتزرع في قاعدة البيانات الحقيقية.

import type { Category, Coupon, Product, Review } from './types';

const daysAgo = (n: number) =>
  new Date(Date.now() - n * 86_400_000).toISOString();

export const categories: Category[] = [
  {
    id: 'cat_oriental',
    slug: 'oriental',
    name: 'عطور شرقية',
    nameEn: 'Oriental',
    description: 'دفء العنبر والعود والبخور',
    iconKey: 'flame',
    sortOrder: 1,
  },
  {
    id: 'cat_french',
    slug: 'french',
    name: 'عطور فرنسية',
    nameEn: 'French',
    description: 'أناقة زهرية وفواكه منعشة',
    iconKey: 'flower',
    sortOrder: 2,
  },
  {
    id: 'cat_oud',
    slug: 'oud',
    name: 'عود ودهن',
    nameEn: 'Oud',
    description: 'دهن العود الخالص والمعتّق',
    iconKey: 'wood',
    sortOrder: 3,
  },
  {
    id: 'cat_niche',
    slug: 'niche',
    name: 'نيتش فاخر',
    nameEn: 'Niche',
    description: 'توقيعات نادرة محدودة الإنتاج',
    iconKey: 'diamond',
    sortOrder: 4,
  },
  {
    id: 'cat_body',
    slug: 'body',
    name: 'بادي ميست وزيوت',
    nameEn: 'Body & Oils',
    description: 'عناية معطّرة خفيفة لليوم',
    iconKey: 'drop',
    sortOrder: 5,
  },
  {
    id: 'cat_gift',
    slug: 'gifts',
    name: 'أطقم وهدايا',
    nameEn: 'Gift Sets',
    description: 'علب مجهّزة للإهداء',
    iconKey: 'gift',
    sortOrder: 6,
  },
];

export const products: Product[] = [
  {
    id: 'p_001',
    slug: 'simat-nuit',
    name: 'سِمة الليل',
    nameEn: 'Simat Nuit',
    brand: 'SIMAT',
    categoryId: 'cat_oriental',
    description:
      'توقيع شرقي دافئ يفتح بالزعفران والهيل ثم يستقر على العنبر وخشب الصندل. مثالي لسهرات الشتاء والمناسبات المسائية.',
    price: 1450,
    oldPrice: 1750,
    sizeMl: 100,
    gender: 'unisex',
    concentration: 'edp',
    topNotes: ['زعفران', 'هيل', 'برغموت'],
    heartNotes: ['ورد طائفي', 'ياسمين'],
    baseNotes: ['عنبر', 'صندل', 'مسك أبيض'],
    longevityHours: 12,
    stock: 34,
    rating: 4.8,
    ratingCount: 126,
    soldCount: 310,
    isFeatured: true,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(180),
  },
  {
    id: 'p_002',
    slug: 'royal-oud',
    name: 'عود ملكي',
    nameEn: 'Royal Oud',
    brand: 'SIMAT',
    categoryId: 'cat_oud',
    description:
      'دهن عود كمبودي معتّق بنسبة عالية، رائحة كثيفة تدوم على الملابس أياماً. يُستخدم بكميات قليلة جداً.',
    price: 3200,
    oldPrice: null,
    sizeMl: 12,
    gender: 'men',
    concentration: 'oil',
    topNotes: ['عود كمبودي'],
    heartNotes: ['ورد بلغاري'],
    baseNotes: ['مسك', 'عنبر أسود'],
    longevityHours: 24,
    stock: 8,
    rating: 4.9,
    ratingCount: 64,
    soldCount: 96,
    isFeatured: true,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(160),
  },
  {
    id: 'p_003',
    slug: 'cairo-jasmine',
    name: 'ياسمين القاهرة',
    nameEn: 'Cairo Jasmine',
    brand: 'SIMAT',
    categoryId: 'cat_french',
    description:
      'ياسمين مصري طبيعي بلمسة فانيليا ناعمة. عطر نهاري أنثوي خفيف ومناسب للعمل والخروجات الصباحية.',
    price: 890,
    oldPrice: null,
    sizeMl: 75,
    gender: 'women',
    concentration: 'edp',
    topNotes: ['ليمون', 'كمثرى'],
    heartNotes: ['ياسمين', 'زهر البرتقال'],
    baseNotes: ['فانيليا', 'مسك'],
    longevityHours: 8,
    stock: 52,
    rating: 4.6,
    ratingCount: 203,
    soldCount: 480,
    isFeatured: true,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(150),
  },
  {
    id: 'p_004',
    slug: 'ambre-noir',
    name: 'أمبر نوار',
    nameEn: 'Ambre Noir',
    brand: 'SIMAT',
    categoryId: 'cat_niche',
    description:
      'عنبر أسود مدخّن مع جلد ولبان. توقيع نيتش جريء لمن يبحث عن حضور مختلف تماماً.',
    price: 2450,
    oldPrice: 2800,
    sizeMl: 50,
    gender: 'unisex',
    concentration: 'parfum',
    topNotes: ['لبان', 'فلفل أسود'],
    heartNotes: ['جلد', 'ورد'],
    baseNotes: ['عنبر أسود', 'باتشولي', 'فيتيفر'],
    longevityHours: 16,
    stock: 15,
    rating: 4.7,
    ratingCount: 48,
    soldCount: 87,
    isFeatured: true,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(120),
  },
  {
    id: 'p_005',
    slug: 'white-musk',
    name: 'مسك الطهارة',
    nameEn: 'White Musk',
    brand: 'SIMAT',
    categoryId: 'cat_body',
    description:
      'مسك أبيض نقي بزيت خفيف، رائحة نظيفة وهادئة تناسب الاستخدام اليومي وتحت الملابس.',
    price: 320,
    oldPrice: null,
    sizeMl: 30,
    gender: 'women',
    concentration: 'oil',
    topNotes: ['مسك أبيض'],
    heartNotes: ['زهر القطن'],
    baseNotes: ['خشب الأرز'],
    longevityHours: 6,
    stock: 120,
    rating: 4.5,
    ratingCount: 310,
    soldCount: 920,
    isFeatured: false,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(140),
  },
  {
    id: 'p_006',
    slug: 'sahara',
    name: 'صحراء',
    nameEn: 'Sahara',
    brand: 'SIMAT',
    categoryId: 'cat_oriental',
    description:
      'رمال دافئة وبخور خفيف مع توابل جافة. عطر رجالي يعطي إحساس الغروب في الصحراء.',
    price: 1180,
    oldPrice: null,
    sizeMl: 100,
    gender: 'men',
    concentration: 'edp',
    topNotes: ['قرفة', 'جوزة الطيب'],
    heartNotes: ['بخور', 'مرمية'],
    baseNotes: ['خشب الأرز', 'عنبر'],
    longevityHours: 10,
    stock: 41,
    rating: 4.4,
    ratingCount: 88,
    soldCount: 205,
    isFeatured: false,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(110),
  },
  {
    id: 'p_007',
    slug: 'rose-de-mai',
    name: 'روز دو ماي',
    nameEn: 'Rose de Mai',
    brand: 'SIMAT',
    categoryId: 'cat_french',
    description:
      'ورد مايو الفرنسي في أنقى صوره، مع ليتشي وفاوانيا. عطر رومانسي راقٍ.',
    price: 1650,
    oldPrice: null,
    sizeMl: 90,
    gender: 'women',
    concentration: 'edp',
    topNotes: ['ليتشي', 'برغموت'],
    heartNotes: ['ورد مايو', 'فاوانيا'],
    baseNotes: ['مسك', 'باتشولي ناعم'],
    longevityHours: 9,
    stock: 27,
    rating: 4.8,
    ratingCount: 141,
    soldCount: 262,
    isFeatured: true,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(100),
  },
  {
    id: 'p_008',
    slug: 'blue-oud',
    name: 'عود أزرق',
    nameEn: 'Blue Oud',
    brand: 'SIMAT',
    categoryId: 'cat_oud',
    description:
      'عود ممزوج بنوتات بحرية منعشة — تركيبة عصرية تكسر ثقل العود التقليدي وتناسب النهار.',
    price: 1950,
    oldPrice: null,
    sizeMl: 100,
    gender: 'men',
    concentration: 'edp',
    topNotes: ['نوتات بحرية', 'جريب فروت'],
    heartNotes: ['عود', 'لافندر'],
    baseNotes: ['عنبر', 'مسك'],
    longevityHours: 11,
    stock: 22,
    rating: 4.6,
    ratingCount: 73,
    soldCount: 149,
    isFeatured: false,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(90),
  },
  {
    id: 'p_009',
    slug: 'madagascar-vanilla',
    name: 'فانيليا مدغشقر',
    nameEn: 'Madagascar Vanilla',
    brand: 'SIMAT',
    categoryId: 'cat_body',
    description:
      'بادي ميست فانيليا كريمية مع كراميل خفيف، إحساس دافئ ومريح طول اليوم.',
    price: 260,
    oldPrice: 340,
    sizeMl: 250,
    gender: 'women',
    concentration: 'mist',
    topNotes: ['كراميل'],
    heartNotes: ['فانيليا بوربون'],
    baseNotes: ['مسك ناعم'],
    longevityHours: 4,
    stock: 200,
    rating: 4.3,
    ratingCount: 420,
    soldCount: 1180,
    isFeatured: false,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(85),
  },
  {
    id: 'p_010',
    slug: 'athar',
    name: 'أثر',
    nameEn: 'Athar',
    brand: 'SIMAT',
    categoryId: 'cat_niche',
    description:
      'إصدار محدود من 500 زجاجة فقط. تركيبة معقّدة من اللبان العُماني والإيريس والجلد الناعم.',
    price: 4100,
    oldPrice: null,
    sizeMl: 50,
    gender: 'unisex',
    concentration: 'parfum',
    topNotes: ['لبان عُماني', 'إلمي'],
    heartNotes: ['إيريس', 'ورد تركي'],
    baseNotes: ['جلد', 'عود', 'مسك حيواني'],
    longevityHours: 20,
    stock: 5,
    rating: 5,
    ratingCount: 19,
    soldCount: 31,
    isFeatured: true,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(60),
  },
  {
    id: 'p_011',
    slug: 'heritage-set',
    name: 'طقم الأصالة',
    nameEn: 'Heritage Set',
    brand: 'SIMAT',
    categoryId: 'cat_gift',
    description:
      'علبة هدايا فاخرة تضم ٣ عطور بحجم ٣٠ مل: سِمة الليل، صحراء، وياسمين القاهرة — مع بطاقة إهداء.',
    price: 2100,
    oldPrice: 2600,
    sizeMl: 90,
    gender: 'unisex',
    concentration: 'edp',
    topNotes: ['تشكيلة'],
    heartNotes: ['تشكيلة'],
    baseNotes: ['تشكيلة'],
    longevityHours: 10,
    stock: 18,
    rating: 4.9,
    ratingCount: 57,
    soldCount: 118,
    isFeatured: true,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(55),
  },
  {
    id: 'p_012',
    slug: 'haram-incense',
    name: 'بخور الحرم',
    nameEn: 'Haram Incense',
    brand: 'SIMAT',
    categoryId: 'cat_oriental',
    description:
      'مزيج بخور تقليدي بالعود والصندل والمستكة، رائحة روحانية هادئة للبيت والمجالس.',
    price: 540,
    oldPrice: null,
    sizeMl: 40,
    gender: 'unisex',
    concentration: 'oil',
    topNotes: ['مستكة'],
    heartNotes: ['بخور', 'صندل'],
    baseNotes: ['عود'],
    longevityHours: 14,
    stock: 64,
    rating: 4.7,
    ratingCount: 165,
    soldCount: 390,
    isFeatured: false,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(50),
  },
  {
    id: 'p_013',
    slug: 'citrus-fresh',
    name: 'سيتروس فريش',
    nameEn: 'Citrus Fresh',
    brand: 'SIMAT',
    categoryId: 'cat_french',
    description:
      'انتعاش حمضي فوري: ليمون صقلي، نعناع، وخشب أبيض. الأفضل لصيف مصر الحار.',
    price: 720,
    oldPrice: null,
    sizeMl: 100,
    gender: 'men',
    concentration: 'edt',
    topNotes: ['ليمون صقلي', 'نعناع'],
    heartNotes: ['زنجبيل', 'لافندر'],
    baseNotes: ['خشب أبيض', 'مسك'],
    longevityHours: 6,
    stock: 76,
    rating: 4.2,
    ratingCount: 232,
    soldCount: 510,
    isFeatured: false,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(45),
  },
  {
    id: 'p_014',
    slug: 'taifi-rose-oil',
    name: 'دهن ورد طائفي',
    nameEn: 'Taifi Rose Oil',
    brand: 'SIMAT',
    categoryId: 'cat_oud',
    description:
      'دهن ورد طائفي مقطّر بالطريقة التقليدية. قطرة واحدة تكفي وتدوم لساعات طويلة.',
    price: 2750,
    oldPrice: null,
    sizeMl: 6,
    gender: 'women',
    concentration: 'oil',
    topNotes: ['ورد طائفي'],
    heartNotes: ['ورد طائفي'],
    baseNotes: ['مسك'],
    longevityHours: 18,
    stock: 11,
    rating: 4.9,
    ratingCount: 41,
    soldCount: 68,
    isFeatured: false,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(40),
  },
  {
    id: 'p_015',
    slug: 'coco-noel',
    name: 'كوكو نويل',
    nameEn: 'Coco Noel',
    brand: 'SIMAT',
    categoryId: 'cat_body',
    description:
      'زيت جوز الهند المعطّر بالفانيليا والتونكا — يرطّب البشرة ويترك أثراً حلواً.',
    price: 295,
    oldPrice: null,
    sizeMl: 100,
    gender: 'women',
    concentration: 'oil',
    topNotes: ['جوز الهند'],
    heartNotes: ['تونكا'],
    baseNotes: ['فانيليا'],
    longevityHours: 5,
    stock: 145,
    rating: 4.4,
    ratingCount: 288,
    soldCount: 760,
    isFeatured: false,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(35),
  },
  {
    id: 'p_016',
    slug: 'imperial',
    name: 'إمبريال',
    nameEn: 'Imperial',
    brand: 'SIMAT',
    categoryId: 'cat_niche',
    description:
      'توقيع رجالي فخم بالتبغ والعسل والويسكي. عطر مناسبات مسائية بحضور طاغٍ.',
    price: 2980,
    oldPrice: null,
    sizeMl: 75,
    gender: 'men',
    concentration: 'parfum',
    topNotes: ['برغموت', 'قرفة'],
    heartNotes: ['تبغ', 'عسل'],
    baseNotes: ['فانيليا', 'خشب مدخّن'],
    longevityHours: 15,
    stock: 13,
    rating: 4.8,
    ratingCount: 52,
    soldCount: 94,
    isFeatured: false,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(30),
  },
  {
    id: 'p_017',
    slug: 'bridal-set',
    name: 'طقم العروس',
    nameEn: 'Bridal Set',
    brand: 'SIMAT',
    categoryId: 'cat_gift',
    description:
      'علبة أنيقة تضم عطر روز دو ماي ١٠٠ مل + بادي ميست + دهن ورد صغير، مغلّفة بالساتان.',
    price: 2650,
    oldPrice: null,
    sizeMl: 100,
    gender: 'women',
    concentration: 'edp',
    topNotes: ['ورد'],
    heartNotes: ['ياسمين'],
    baseNotes: ['مسك'],
    longevityHours: 10,
    stock: 9,
    rating: 4.9,
    ratingCount: 34,
    soldCount: 61,
    isFeatured: false,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(25),
  },
  {
    id: 'p_018',
    slug: 'sea-breeze',
    name: 'نسيم البحر',
    nameEn: 'Sea Breeze',
    brand: 'SIMAT',
    categoryId: 'cat_french',
    description:
      'نوتات مائية وملح البحر مع خشب طافٍ — عطر صيفي خفيف للجنسين.',
    price: 680,
    oldPrice: null,
    sizeMl: 100,
    gender: 'unisex',
    concentration: 'edt',
    topNotes: ['ملح البحر', 'برغموت'],
    heartNotes: ['نوتات مائية', 'ميرمية'],
    baseNotes: ['خشب طافٍ', 'مسك'],
    longevityHours: 6,
    stock: 88,
    rating: 4.1,
    ratingCount: 176,
    soldCount: 402,
    isFeatured: false,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(20),
  },
  {
    id: 'p_019',
    slug: 'saffron-royal',
    name: 'زعفران رويال',
    nameEn: 'Saffron Royal',
    brand: 'SIMAT',
    categoryId: 'cat_oriental',
    description:
      'زعفران إيراني فاخر مع جلد وعنبر. تركيبة غنية جداً تحتاج بختين بس.',
    price: 1890,
    oldPrice: null,
    sizeMl: 75,
    gender: 'unisex',
    concentration: 'edp',
    topNotes: ['زعفران', 'جوزة الطيب'],
    heartNotes: ['جلد', 'ورد'],
    baseNotes: ['عنبر', 'عود'],
    longevityHours: 13,
    stock: 0,
    rating: 4.7,
    ratingCount: 97,
    soldCount: 188,
    isFeatured: false,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(15),
  },
  {
    id: 'p_020',
    slug: 'simat-edition-2026',
    name: 'سِمة إيديشن ٢٠٢٦',
    nameEn: 'Simat Edition 2026',
    brand: 'SIMAT',
    categoryId: 'cat_niche',
    description:
      'الإصدار السنوي الجديد: إيريس ودود وفلفل وردي في زجاجة مرقّمة يدوياً.',
    price: 3450,
    oldPrice: null,
    sizeMl: 100,
    gender: 'unisex',
    concentration: 'parfum',
    topNotes: ['فلفل وردي', 'برغموت'],
    heartNotes: ['إيريس', 'ورد'],
    baseNotes: ['دود', 'مسك', 'صندل'],
    longevityHours: 14,
    stock: 24,
    rating: 4.9,
    ratingCount: 12,
    soldCount: 23,
    isFeatured: true,
    isActive: true,
    imageUrl: null,
    createdAt: daysAgo(6),
  },
];

export const coupons: Coupon[] = [
  {
    code: 'SIMAT10',
    type: 'percent',
    value: 10,
    minOrder: 800,
    maxDiscount: 400,
    expiresAt: daysAgo(-90),
    usageLimit: 500,
    usedCount: 128,
    isActive: true,
  },
  {
    code: 'WELCOME50',
    type: 'fixed',
    value: 50,
    minOrder: 300,
    maxDiscount: null,
    expiresAt: daysAgo(-180),
    usageLimit: 0,
    usedCount: 340,
    isActive: true,
  },
  {
    code: 'OUD15',
    type: 'percent',
    value: 15,
    minOrder: 2000,
    maxDiscount: 700,
    expiresAt: daysAgo(-30),
    usageLimit: 100,
    usedCount: 22,
    isActive: true,
  },
];

const reviewNames = [
  'منى سعيد',
  'كريم عبد الله',
  'سارة الشناوي',
  'يوسف حسن',
  'نورهان فتحي',
  'محمد الشريف',
];

const reviewComments = [
  'ثبات ممتاز والرائحة فخمة جداً، هطلب تاني أكيد.',
  'التغليف راقي والتوصيل كان سريع. تسلم إيديكم.',
  'أفضل عطر جربته من فترة طويلة، بجد يستاهل.',
  'اشتريته هدية والشخص انبسط جداً بيه.',
  'الرائحة حلوة بس الثبات أقل من المتوقع شوية.',
];

/** تقييمات ثابتة (مش عشوائية) عشان الصفحات تتولّد بنفس المحتوى. */
export const reviews: Review[] = products.flatMap((product, i) =>
  [0, 1, 2].map((j) => ({
    id: `r_${product.id}_${j}`,
    productId: product.id,
    userName: reviewNames[(i + j) % reviewNames.length],
    rating: [5, 5, 4, 5, 4, 3][(i + j) % 6],
    comment: reviewComments[(i * 2 + j) % reviewComments.length],
    createdAt: daysAgo(7 + ((i * 5 + j * 3) % 90)),
  })),
);
