-- ═══════════════════════════════════════════════════════════════
--  SIMAT — بيانات المتجر الابتدائية
--  مولّد تلقائياً من src/lib/seed.ts — متعدّلش الملف ده بإيدك.
--  شغّله بعد schema.sql في: Supabase → SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- إعدادات عامة
insert into public.settings (key, value) values
  ('free_shipping_threshold', '1500')
on conflict (key) do update set value = excluded.value;

-- أسعار الشحن
insert into public.shipping_rates (governorate, price) values
  ('القاهرة', 50),
  ('الجيزة', 50),
  ('القليوبية', 55),
  ('الإسكندرية', 65),
  ('الدقهلية', 70),
  ('الشرقية', 70),
  ('الغربية', 70),
  ('المنوفية', 70),
  ('البحيرة', 75),
  ('كفر الشيخ', 75),
  ('دمياط', 75),
  ('بورسعيد', 75),
  ('الإسماعيلية', 75),
  ('السويس', 75),
  ('الفيوم', 80),
  ('بني سويف', 80),
  ('المنيا', 85),
  ('أسيوط', 90),
  ('سوهاج', 95),
  ('قنا', 100),
  ('الأقصر', 105),
  ('أسوان', 110),
  ('البحر الأحمر', 120),
  ('مطروح', 120),
  ('شمال سيناء', 130),
  ('جنوب سيناء', 130),
  ('الوادي الجديد', 130)
on conflict (governorate) do update set price = excluded.price;

-- التصنيفات
insert into public.categories
  (id, slug, name, name_en, description, description_en, icon_key, sort_order) values
  ('cat_signature', 'signature', 'عطور سِمة', 'SIMAT Fragrances', 'ماء عطر بأحجام 40 و60 و100 مل', 'Eau de Parfum in 40, 60 and 100 ml', 'bottle', 1),
  ('cat_discovery', 'discovery', 'أطقم العينات', 'Discovery Sets', 'جرب في البيت قبل ما تقرر', 'Try at home before you decide', 'gift', 2)
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, name_en = excluded.name_en,
  description = excluded.description, description_en = excluded.description_en,
  icon_key = excluded.icon_key, sort_order = excluded.sort_order,
  is_active = true;

-- المنتجات
insert into public.products
  (id, slug, name, name_en, brand, category_id, description, description_en,
   family, family_en, kind, label_style, secondary_line, tagline_en,
   short_description_en, scent_character_en, accords_en, wear_profile_en,
   occasion_en, related, variants, image_hover_url, price,
   old_price, size_ml, gender, concentration, top_notes, heart_notes,
   base_notes, top_notes_en, heart_notes_en, base_notes_en,
   longevity_hours, stock, rating, rating_count, sold_count,
   is_featured, is_active, image_url, created_at) values
  ('nocturne', 'nocturne', 'SIMAT NOCTURNE', 'SIMAT NOCTURNE', 'SIMAT',
   'cat_signature', '', 'SIMAT NOCTURNE is a captivating blend of adrenaline-rich coffee and sweet vanilla, creating a bold and mesmerizing scent for the modern woman.',
   '', 'Amber Vanilla', 'bottle', 'bordeaux',
   'Inspired by Black Opium', 'Awaken the night.', 'A highly addictive, seductive amber vanilla fragrance.',
   'Seductive, Energetic, Bold', array['Vanilla','Coffee','Sweet']::text[], 'An intoxicating gourmand floral that commands attention.',
   'Evening wear, Night out', array['duality','alter','velvet-ego']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Pear','Pink Pepper','Orange Blossom']::text[], array['Coffee','Jasmine','Bitter Almond']::text[], array['Vanilla','Patchouli','Cedar']::text[],
   8, 50, 0, 0,
   100, true, true,
   null, '2026-10-04T14:07:26.441Z'),
  ('anima', 'anima', 'SIMAT ANIMA', 'SIMAT ANIMA', 'SIMAT',
   'cat_signature', '', 'SIMAT ANIMA captures the essence of classic luxury with a complex blend of warm spices, rich amber, and delicate florals.',
   '', 'Amber Spicy', 'bottle', 'bordeaux',
   'Inspired by Coco Chanel', 'Timeless elegance redefined.', 'A classic, warm spicy amber fragrance that exudes sophistication.',
   'Elegant, Classic, Sophisticated', array['Amber','Woody','Warm Spicy']::text[], 'A rich and opulent scent that lingers beautifully.',
   'Formal events, Signature scent', array['velvet-ego','libera','aura']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Coriander','Mandarin Orange']::text[], array['Mimosa','Cloves','Orange Blossom']::text[], array['Labdanum','Amber','Sandalwood']::text[],
   8, 50, 0, 0,
   58, false, true,
   null, '2026-10-03T14:07:26.441Z'),
  ('velvet-ego', 'velvet-ego', 'SIMAT VELVET EGO', 'SIMAT VELVET EGO', 'SIMAT',
   'cat_signature', '', 'SIMAT VELVET EGO is a statement of pure glamour. Radiant pink pepper and African orange flower melt into a warm, sensual vanilla base.',
   '', 'Amber Floral', 'bottle', 'bordeaux',
   'Inspired by Roberto Cavalli', 'Embrace your boldest self.', 'An opulent white floral and amber fragrance.',
   'Sensual, Glamorous, Radiant', array['White Floral','Amber']::text[], 'A radiant floral that leaves a golden trail.',
   'Special occasions, Evening', array['anima','nocturne','duality']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Pink Pepper']::text[], array['African Orange Flower']::text[], array['Vanilla','Benzoin']::text[],
   8, 50, 0, 0,
   57, false, true,
   null, '2026-10-02T14:07:26.441Z'),
  ('alter', 'alter', 'SIMAT ALTER', 'SIMAT ALTER', 'SIMAT',
   'cat_signature', '', 'SIMAT ALTER is a playful yet powerful fragrance. Delicious honey and vibrant blood orange create an irresistible and daring signature.',
   '', 'Chypre Floral', 'bottle', 'linen',
   'Inspired by Scandal', 'Break the rules.', 'A sweet, honeyed chypre floral that is delightfully provocative.',
   'Playful, Provocative, Sweet', array['Honey','Sweet','White Floral']::text[], 'A delicious and daring honey-floral blend.',
   'Date night, Parties', array['euphoria','reverie','memoria']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Blood Orange','Mandarin Orange']::text[], array['Honey','Gardenia','Orange Blossom']::text[], array['Beeswax','Caramel','Patchouli']::text[],
   8, 50, 0, 0,
   56, false, true,
   null, '2026-10-01T14:07:26.441Z'),
  ('euphoria', 'euphoria', 'SIMAT EUPHORIA', 'SIMAT EUPHORIA', 'SIMAT',
   'cat_signature', '', 'SIMAT EUPHORIA is a celebration of happiness. Sparkling iris and sweet praline combine to create a radiant, universally loved fragrance.',
   '', 'Floral Fruity Gourmand', 'bottle', 'linen',
   'Inspired by La Vie Est Belle', 'Life is beautiful.', 'A joyful floral fruity gourmand with a sweet vanilla trail.',
   'Joyful, Radiant, Feminine', array['Sweet','Vanilla','Fruity']::text[], 'A sweet, luminous scent that brings joy.',
   'Everyday wear, Daytime', array['alter','memoria','cloud']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Black Currant','Pear']::text[], array['Iris','Jasmine','Orange Blossom']::text[], array['Praline','Vanilla','Patchouli']::text[],
   8, 50, 0, 0,
   55, false, true,
   null, '2026-09-30T14:07:26.441Z'),
  ('reverie', 'reverie', 'SIMAT REVERIE', 'SIMAT REVERIE', 'SIMAT',
   'cat_signature', '', 'SIMAT REVERIE is a delicious treat for the senses, blending fresh strawberries with golden shortcake and whipped cream.',
   '', 'Gourmand', 'bottle', 'linen',
   'Inspired by Strawberry Pound Cake', 'Indulge in sweet dreams.', 'A comforting, sweet gourmand fragrance.',
   'Sweet, Comforting', array['Sweet','Strawberry','Vanilla']::text[], 'A mouth-watering dessert-like fragrance.',
   'Casual wear', array['euphoria','cloud','spark']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Fresh Strawberries']::text[], array['Golden Shortcake']::text[], array['Whipped Cream','Vanilla']::text[],
   8, 50, 0, 0,
   54, false, true,
   null, '2026-09-29T14:07:26.441Z'),
  ('pulse', 'pulse', 'SIMAT PULSE', 'SIMAT PULSE', 'SIMAT',
   'cat_signature', '', 'SIMAT PULSE transports you to a sun-drenched beach with its exotic blend of guava, coconut, and warm sand notes.',
   '', 'Floral Fruity', 'bottle', 'linen',
   'Inspired by Very Sexy Now', 'Feel the heat.', 'A vibrant, tropical floral fruity fragrance.',
   'Tropical, Vibrant', array['Fruity','Sweet','Tropical']::text[], 'A sun-kissed, exotic aroma.',
   'Summer days, Vacations', array['serenity','soften','liminal']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Guava','Coconut']::text[], array['Mariposa Flower']::text[], array['Warm Sand','Musk']::text[],
   8, 50, 0, 0,
   53, false, true,
   null, '2026-09-28T14:07:26.441Z'),
  ('duality', 'duality', 'SIMAT DUALITY', 'SIMAT DUALITY', 'SIMAT',
   'cat_signature', '', 'SIMAT DUALITY contrasts the sweet allure of jasmine with the dark mystery of cocoa and tonka bean.',
   '', 'Amber Floral', 'bottle', 'bordeaux',
   'Inspired by Good Girl', 'Embrace your dual nature.', 'A mysterious and elegant amber floral fragrance.',
   'Mysterious, Elegant', array['White Floral','Warm Spicy']::text[], 'A captivating dance of light and dark notes.',
   'Evening, Signature scent', array['nocturne','anima','velvet-ego']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Almond','Coffee','Bergamot']::text[], array['Tuberose','Jasmine Sambac']::text[], array['Tonka Bean','Cacao','Vanilla']::text[],
   8, 50, 0, 0,
   65, true, true,
   null, '2026-09-27T14:07:26.441Z'),
  ('libera', 'libera', 'SIMAT LIBERA', 'SIMAT LIBERA', 'SIMAT',
   'cat_signature', '', 'SIMAT LIBERA blends aromatic lavender with sensual orange blossom for a bold, empowering fragrance.',
   '', 'Amber Fougere', 'bottle', 'bordeaux',
   'Inspired by Libre', 'The scent of freedom.', 'A fierce and clean amber fougere.',
   'Fierce, Independent', array['White Floral','Citrus','Lavender']::text[], 'A sharp, clean, and empowering scent.',
   'Office wear, Everyday', array['identity','clarity','aura']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Lavender','Mandarin Orange']::text[], array['Lavender','Orange Blossom']::text[], array['Madagascar Vanilla','Musk']::text[],
   8, 50, 0, 0,
   51, false, true,
   null, '2026-09-26T14:07:26.441Z'),
  ('memoria', 'memoria', 'SIMAT MEMORIA', 'SIMAT MEMORIA', 'SIMAT',
   'cat_signature', '', 'SIMAT MEMORIA is a burst of vibrant berries settling into a soft, musky, and woody base.',
   '', 'Floral Fruity Gourmand', 'bottle', 'linen',
   'Inspired by Burberry Her', 'Capture the moment.', 'A youthful, fruity gourmand fragrance.',
   'Youthful, Urban', array['Fruity','Sweet','Woody']::text[], 'A sweet, berry-forward modern scent.',
   'Daytime, Casual', array['euphoria','reverie','spark']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Strawberry','Raspberry']::text[], array['Violet','Jasmine']::text[], array['Musk','Vanilla','Cashmeran']::text[],
   8, 50, 0, 0,
   50, false, true,
   null, '2026-09-25T14:07:26.441Z'),
  ('soften', 'soften', 'SIMAT SOFTEN', 'SIMAT SOFTEN', 'SIMAT',
   'cat_signature', '', 'SIMAT SOFTEN is a gentle embrace of fresh quince and delicate florals, perfect for a subtle, romantic aura.',
   '', 'Floral Fruity', 'bottle', 'linen',
   'Inspired by Tender', 'Delicate and fresh.', 'A romantic floral fruity fragrance.',
   'Delicate, Romantic', array['Fresh','Floral','Citrus']::text[], 'A soft, airy, and romantic blend.',
   'Spring days, Dates', array['pulse','serenity','pearl']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Grapefruit','Quince']::text[], array['Jasmine','Hyacinth']::text[], array['Musk','Iris','Cedar']::text[],
   8, 50, 0, 0,
   49, false, true,
   null, '2026-09-24T14:07:26.441Z'),
  ('liminal', 'liminal', 'SIMAT LIMINAL', 'SIMAT LIMINAL', 'SIMAT',
   'cat_signature', '', 'SIMAT LIMINAL captures the essence of the ocean breeze mixed with fresh melon and delicate florals.',
   '', 'Floral Aquatic', 'bottle', 'linen',
   'Inspired by Escape', 'Find your sanctuary.', 'A refreshing floral aquatic fragrance.',
   'Aquatic, Free', array['Fruity','Floral','Aquatic']::text[], 'A crisp, refreshing aquatic scent.',
   'Summer, Casual', array['flow','pulse','soften']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Melon','Chamomile']::text[], array['Peach','Lily-of-the-Valley']::text[], array['Oakmoss','Musk','Amber']::text[],
   8, 50, 0, 0,
   48, false, true,
   null, '2026-09-23T14:07:26.441Z'),
  ('aura', 'aura', 'SIMAT AURA', 'SIMAT AURA', 'SIMAT',
   'cat_signature', '', 'SIMAT AURA is a unique blend of salty vanilla and water jasmine, creating a powerful and addictive signature.',
   '', 'Amber Floral', 'bottle', 'bordeaux',
   'Inspired by Olympia', 'Unleash your inner goddess.', 'A divine, salty amber floral.',
   'Divine, Powerful', array['Vanilla','Salty','White Floral']::text[], 'A unique salty-sweet floral.',
   'Signature scent, Evening', array['anima','libera','velvet-ego']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Water Jasmine','Green Mandarin']::text[], array['Vanilla','Salt']::text[], array['Ambergris','Cashmere Wood']::text[],
   8, 50, 0, 0,
   47, false, true,
   null, '2026-09-22T14:07:26.441Z'),
  ('psyche', 'psyche', 'SIMAT PSYCHE', 'SIMAT PSYCHE', 'SIMAT',
   'cat_signature', '', 'SIMAT PSYCHE is a beautifully balanced composition of white flowers and bright citrus notes.',
   '', 'Floral', 'bottle', 'linen',
   'Inspired by Georgina', 'Pure floral elegance.', 'A fresh and elegant floral fragrance.',
   'Elegant, Fresh', array['Floral','Fresh']::text[], 'A clean, bright floral bouquet.',
   'Office, Everyday', array['soften','memoria','pearl']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Citrus Notes']::text[], array['White Flowers']::text[], array['Musk','Woods']::text[],
   8, 50, 0, 0,
   46, false, true,
   null, '2026-09-21T14:07:26.441Z'),
  ('serenity', 'serenity', 'SIMAT SERENITY', 'SIMAT SERENITY', 'SIMAT',
   'cat_signature', '', 'SIMAT SERENITY is a burst of juicy lychee and raspberry, balanced by soft white rose and vanilla.',
   '', 'Floral Fruity', 'bottle', 'linen',
   'Inspired by Mayar', 'Vibrant and sweet.', 'A lively floral fruity fragrance.',
   'Vibrant, Sweet', array['Fruity','Sweet','Fresh']::text[], 'A juicy, mouth-watering fruity scent.',
   'Daytime, Summer', array['pulse','spark','reverie']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Lychee','Raspberry']::text[], array['White Rose','Jasmine']::text[], array['Vanilla','Musk']::text[],
   8, 50, 0, 0,
   45, false, true,
   null, '2026-09-20T14:07:26.441Z'),
  ('comfort', 'comfort', 'SIMAT COMFORT', 'SIMAT COMFORT', 'SIMAT',
   'cat_signature', '', 'SIMAT COMFORT is like a warm hug, featuring rich caramel, honey, and creamy vanilla.',
   '', 'Amber Gourmand', 'bottle', 'velvet',
   'Inspired by Bianco Latte', 'Wrap yourself in warmth.', 'A cozy, sweet amber gourmand.',
   'Cozy, Warm', array['Vanilla','Sweet','Caramel']::text[], 'A comforting, milky-sweet aroma.',
   'Fall/Winter, Cozy nights', array['reverie','soma','cloud']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Caramel']::text[], array['Coumarin','Honey']::text[], array['Vanilla','White Musk']::text[],
   8, 50, 0, 0,
   44, false, true,
   null, '2026-09-19T14:07:26.441Z'),
  ('soma', 'soma', 'SIMAT SOMA', 'SIMAT SOMA', 'SIMAT',
   'cat_signature', '', 'SIMAT SOMA is an opulent blend of cinnamon, dates, and praline, perfect for making a statement.',
   '', 'Amber Spicy', 'bottle', 'velvet',
   'Inspired by Khamrah', 'Rich, spicy, and decadent.', 'A luxurious amber spicy fragrance.',
   'Decadent, Rich', array['Sweet','Warm Spicy','Woody']::text[], 'A rich, spicy, and sweet oriental blend.',
   'Evening, Winter', array['comfort','obsession','imperium']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Cinnamon','Nutmeg','Bergamot']::text[], array['Dates','Praline','Tuberose']::text[], array['Vanilla','Tonka Bean','Myrrh']::text[],
   8, 50, 0, 0,
   80, true, true,
   null, '2026-09-18T14:07:26.441Z'),
  ('limen', 'limen', 'SIMAT LIMEN', 'SIMAT LIMEN', 'SIMAT',
   'cat_signature', '', 'SIMAT LIMEN balances fresh citrus and lavender with a deep, woody base.',
   '', 'Woody Aromatic', 'bottle', 'velvet',
   'Inspired by Reef 33', 'Fresh and aromatic.', 'A crisp woody aromatic fragrance.',
   'Fresh, Woody', array['Aromatic','Woody','Fresh Spicy']::text[], 'A clean, aromatic, and grounded scent.',
   'Everyday, Office', array['ground','clarity','identity']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Bergamot','Lemon']::text[], array['Lavender','Rosemary']::text[], array['Oud','Vetiver','Musk']::text[],
   8, 50, 0, 0,
   42, false, true,
   null, '2026-09-17T14:07:26.441Z'),
  ('imprint', 'imprint', 'SIMAT IMPRINT', 'SIMAT IMPRINT', 'SIMAT',
   'cat_signature', '', 'SIMAT IMPRINT is a mesmerizing and luxurious blend of saffron, amberwood, and cedar.',
   '', 'Amber Floral', 'bottle', 'velvet',
   'Inspired by Baccarat Rouge 540', 'Leave a lasting impression.', 'A radiant amber floral fragrance.',
   'Luxurious, Radiant', array['Woody','Amber','Warm Spicy']::text[], 'A glowing, airy, and sweet woody scent.',
   'Signature scent, Special events', array['soma','ascend','nexus']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Saffron','Jasmine']::text[], array['Amberwood','Ambergris']::text[], array['Fir Resin','Cedar']::text[],
   8, 50, 0, 0,
   95, true, true,
   null, '2026-09-16T14:07:26.441Z'),
  ('ascend', 'ascend', 'SIMAT ASCEND', 'SIMAT ASCEND', 'SIMAT',
   'cat_signature', '', 'SIMAT ASCEND is an intense and sweet blend of vanilla, incense, and tonka bean.',
   '', 'Amber Woody', 'bottle', 'noir',
   'Inspired by Invictus Victory Elixir', 'Rise to the top.', 'A powerful amber woody fragrance.',
   'Powerful, Intense', array['Vanilla','Amber','Sweet']::text[], 'A strong, sweet, and victorious aroma.',
   'Night out, Clubbing', array['apex','magnet','poise']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Lavender','Cardamom']::text[], array['Incense','Patchouli']::text[], array['Vanilla Bean','Tonka Bean']::text[],
   8, 50, 0, 0,
   40, false, true,
   null, '2026-09-15T14:07:26.441Z'),
  ('ground', 'ground', 'SIMAT GROUND', 'SIMAT GROUND', 'SIMAT',
   'cat_signature', '', 'SIMAT GROUND combines sparkling citrus with earthy vetiver and pepper for a sophisticated profile.',
   '', 'Woody Spicy', 'bottle', 'noir',
   'Inspired by Terre d''Hermès', 'Earthy and grounded.', 'A classic woody spicy fragrance.',
   'Earthy, Sophisticated', array['Citrus','Woody','Earthy']::text[], 'A mature, earthy, and citrusy blend.',
   'Office, Signature scent', array['clarity','limen','identity']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Orange','Grapefruit']::text[], array['Pepper','Pelargonium']::text[], array['Vetiver','Cedar','Patchouli']::text[],
   8, 50, 0, 0,
   39, false, true,
   null, '2026-09-14T14:07:26.441Z'),
  ('shadow', 'shadow', 'SIMAT SHADOW', 'SIMAT SHADOW', 'SIMAT',
   'cat_signature', '', 'SIMAT SHADOW is an intense, hypnotic blend of resins, woods, and smoky incense.',
   '', 'Woody Aromatic', 'bottle', 'velvet',
   'Inspired by Black Afgano', 'Embrace the mystery.', 'A dark, smoky woody aromatic fragrance.',
   'Dark, Mysterious', array['Woody','Smoky','Balsamic']::text[], 'A deep, dark, and intoxicating scent.',
   'Evening, Winter', array['dark-matter','umbra','regal']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Cannabis','Green Notes']::text[], array['Resins','Woodsy Notes']::text[], array['Incense','Agarwood (Oud)']::text[],
   8, 50, 0, 0,
   38, false, true,
   null, '2026-09-13T14:07:26.441Z'),
  ('temper', 'temper', 'SIMAT TEMPER', 'SIMAT TEMPER', 'SIMAT',
   'cat_signature', '', 'SIMAT TEMPER is a daring contrast of fresh mandarin and violet against warm leather and woods.',
   '', 'Aromatic Fougere', 'bottle', 'noir',
   'Inspired by Fahrenheit', 'Bold and fiery.', 'A unique aromatic fougere with leather notes.',
   'Bold, Fiery', array['Leather','Woody','Fresh Spicy']::text[], 'A hot, leathery, and unmistakable aroma.',
   'Signature scent, Night out', array['impulse','rebel','obsidian']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Nutmeg Flower','Lavender']::text[], array['Violet Leaf','Nutmeg']::text[], array['Leather','Vetiver','Musk']::text[],
   8, 50, 0, 0,
   37, false, true,
   null, '2026-09-12T14:07:26.441Z'),
  ('obsession', 'obsession', 'SIMAT OBSESSION', 'SIMAT OBSESSION', 'SIMAT',
   'cat_signature', '', 'SIMAT OBSESSION is a decadent pairing of dark rose and sweet praline over a deep oud base.',
   '', 'Amber Woody', 'bottle', 'velvet',
   'Inspired by Oud Bouquet', 'A luxurious floral oriental.', 'A rich amber woody fragrance.',
   'Luxurious, Romantic', array['Oud','Rose','Vanilla']::text[], 'A sweet, rosy, and woody masterpiece.',
   'Evening, Special occasions', array['resonance','soma','mood']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Saffron']::text[], array['Rose']::text[], array['Agarwood (Oud)','Praline']::text[],
   8, 50, 0, 0,
   36, false, true,
   null, '2026-09-11T14:07:26.441Z'),
  ('sovereign', 'sovereign', 'SIMAT SOVEREIGN', 'SIMAT SOVEREIGN', 'SIMAT',
   'cat_signature', '', 'SIMAT SOVEREIGN commands attention with its rich blend of tobacco, spices, and dark woods.',
   '', 'Woody Spicy', 'bottle', 'velvet',
   'Inspired by Oud Malaki', 'Regal and spicy.', 'A sophisticated woody spicy fragrance.',
   'Regal, Sophisticated', array['Tobacco','Woody','Warm Spicy']::text[], 'A warm, spicy, and masculine scent.',
   'Formal events, Winter', array['tobacco','imperium','regal']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Grapefruit','Lavender']::text[], array['Tobacco','Spices']::text[], array['Agarwood (Oud)','Dark Woods']::text[],
   8, 50, 0, 0,
   35, false, true,
   null, '2026-09-10T14:07:26.441Z'),
  ('attach', 'attach', 'SIMAT ATTACH', 'SIMAT ATTACH', 'SIMAT',
   'cat_signature', '', 'SIMAT ATTACH is a cozy, addictive blend of pink pepper, toffee, and warm amber.',
   '', 'Amber Fougere', 'bottle', 'noir',
   'Inspired by Stronger With You Intensely', 'Warm and inviting.', 'A sweet amber fougere fragrance.',
   'Warm, Inviting', array['Sweet','Vanilla','Warm Spicy']::text[], 'A sweet, spicy, and comforting aroma.',
   'Date night, Fall/Winter', array['nostalgia','poise','ascend']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Pink Pepper','Juniper']::text[], array['Toffee','Cinnamon','Lavender']::text[], array['Vanilla','Tonka Bean','Amber']::text[],
   8, 50, 0, 0,
   34, false, true,
   null, '2026-09-09T14:07:26.441Z'),
  ('identity', 'identity', 'SIMAT IDENTITY', 'SIMAT IDENTITY', 'SIMAT',
   'cat_signature', '', 'SIMAT IDENTITY is the perfect balance of fresh apple, aromatic sage, and deep amberwood.',
   '', 'Aromatic Fougere', 'bottle', 'noir',
   'Inspired by YSL Y', 'Modern and fresh.', 'A crisp aromatic fougere fragrance.',
   'Modern, Fresh', array['Aromatic','Fresh Spicy','Woody']::text[], 'A versatile, fresh, and modern scent.',
   'Everyday, Signature scent', array['clarity','instinct','flow']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Apple','Ginger','Bergamot']::text[], array['Sage','Juniper Berries']::text[], array['Amberwood','Tonka Bean']::text[],
   8, 50, 0, 0,
   33, false, true,
   null, '2026-09-08T14:07:26.441Z'),
  ('provocateur', 'provocateur', 'SIMAT PROVOCATEUR', 'SIMAT PROVOCATEUR', 'SIMAT',
   'cat_signature', '', 'SIMAT PROVOCATEUR is a daring and energetic blend of caramel, tonka bean, and clary sage.',
   '', 'Amber Woody', 'bottle', 'noir',
   'Inspired by Scandal Pour Homme', 'Bold and playful.', 'A sweet amber woody fragrance.',
   'Bold, Playful', array['Caramel','Sweet','Aromatic']::text[], 'A sweet, aromatic, and confident aroma.',
   'Night out, Parties', array['magnet','attach','ascend']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Clary Sage','Mandarin Orange']::text[], array['Caramel','Tonka Bean']::text[], array['Vetiver']::text[],
   8, 50, 0, 0,
   32, false, true,
   null, '2026-09-07T14:07:26.441Z'),
  ('clarity', 'clarity', 'SIMAT CLARITY', 'SIMAT CLARITY', 'SIMAT',
   'cat_signature', '', 'SIMAT CLARITY is a timeless composition of fresh grapefruit, ginger, and deep incense.',
   '', 'Woody Aromatic', 'bottle', 'noir',
   'Inspired by Bleu de Chanel', 'Elegant and crisp.', 'A classic woody aromatic fragrance.',
   'Elegant, Crisp', array['Citrus','Woody','Warm Spicy']::text[], 'A clean, sophisticated, and versatile scent.',
   'Office, Signature scent', array['identity','ground','instinct']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Grapefruit','Lemon','Mint']::text[], array['Ginger','Nutmeg','Jasmine']::text[], array['Incense','Vetiver','Cedar']::text[],
   8, 50, 0, 0,
   90, true, true,
   null, '2026-09-06T14:07:26.441Z'),
  ('impulse', 'impulse', 'SIMAT IMPULSE', 'SIMAT IMPULSE', 'SIMAT',
   'cat_signature', '', 'SIMAT IMPULSE is a fiery detonation of spices, cinnamon, and tobacco.',
   '', 'Woody Spicy', 'bottle', 'noir',
   'Inspired by Spicebomb', 'Explosive and warm.', 'A dynamic woody spicy fragrance.',
   'Explosive, Warm', array['Warm Spicy','Cinnamon','Tobacco']::text[], 'A hot, spicy, and captivating aroma.',
   'Winter, Night out', array['temper','rebel','feral']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Pink Pepper','Elemi']::text[], array['Cinnamon','Saffron','Paprika']::text[], array['Tobacco','Leather','Vetiver']::text[],
   8, 50, 0, 0,
   30, false, true,
   null, '2026-09-05T14:07:26.441Z'),
  ('dark-matter', 'dark-matter', 'SIMAT DARK MATTER', 'SIMAT DARK MATTER', 'SIMAT',
   'cat_signature', '', 'SIMAT DARK MATTER takes the smoky, resinous DNA of the original to even darker depths.',
   '', 'Woody Aromatic', 'bottle', 'velvet',
   'Inspired by Black Afgano Deep', 'Intense and smoky.', 'A profound woody aromatic fragrance.',
   'Intense, Smoky', array['Woody','Smoky','Balsamic']::text[], 'An incredibly deep and mysterious scent.',
   'Evening, Winter', array['shadow','umbra','regal']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Cannabis','Green Notes']::text[], array['Resins','Woodsy Notes']::text[], array['Incense','Agarwood (Oud)']::text[],
   8, 50, 0, 0,
   29, false, true,
   null, '2026-09-04T14:07:26.441Z'),
  ('nostalgia', 'nostalgia', 'SIMAT NOSTALGIA', 'SIMAT NOSTALGIA', 'SIMAT',
   'cat_signature', '', 'SIMAT NOSTALGIA is a comforting, luxurious blend of sweet vanilla and rich tobacco leaf.',
   '', 'Amber Spicy', 'bottle', 'velvet',
   'Inspired by Tobacco Vanille', 'Classic and rich.', 'A warm amber spicy fragrance.',
   'Classic, Rich', array['Vanilla','Sweet','Tobacco']::text[], 'A sweet, spicy, and nostalgic aroma.',
   'Fall/Winter, Cozy evenings', array['sovereign','tobacco','attach']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Tobacco Leaf','Spicy Notes']::text[], array['Vanilla','Cacao','Tonka Bean']::text[], array['Dried Fruits','Woody Notes']::text[],
   8, 50, 0, 0,
   28, false, true,
   null, '2026-09-03T14:07:26.441Z'),
  ('flow', 'flow', 'SIMAT FLOW', 'SIMAT FLOW', 'SIMAT',
   'cat_signature', '', 'SIMAT FLOW captures the essence of the sea with crisp marine notes, lime, and white musk.',
   '', 'Aromatic Aquatic', 'bottle', 'noir',
   'Inspired by Acqua di Giò', 'Fresh and marine.', 'A refreshing aromatic aquatic fragrance.',
   'Fresh, Marine', array['Citrus','Aromatic','Marine']::text[], 'A clean, aquatic, and breezy scent.',
   'Summer, Casual', array['liminal','clarity','identity']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Lime','Lemon','Bergamot']::text[], array['Sea Notes','Jasmine']::text[], array['White Musk','Cedar','Oakmoss']::text[],
   8, 50, 0, 0,
   27, false, true,
   null, '2026-09-02T14:07:26.441Z'),
  ('instinct', 'instinct', 'SIMAT INSTINCT', 'SIMAT INSTINCT', 'SIMAT',
   'cat_signature', '', 'SIMAT INSTINCT is a radically fresh composition of spicy pepper, bergamot, and rich ambroxan.',
   '', 'Aromatic Fougere', 'bottle', 'noir',
   'Inspired by Sauvage', 'Wild and fresh.', 'A sharp aromatic fougere fragrance.',
   'Wild, Fresh', array['Fresh Spicy','Amber','Citrus']::text[], 'A crisp, spicy, and highly versatile aroma.',
   'Everyday, Signature scent', array['identity','feral','clarity']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Calabrian Bergamot','Pepper']::text[], array['Sichuan Pepper','Lavender']::text[], array['Ambroxan','Cedar','Labdanum']::text[],
   8, 50, 0, 0,
   85, true, true,
   null, '2026-09-01T14:07:26.441Z'),
  ('root', 'root', 'SIMAT ROOT', 'SIMAT ROOT', 'SIMAT',
   'cat_signature', '', 'SIMAT ROOT is a beautiful blend of sweet peach, apple blossom, and a soft musky base.',
   '', 'Floral Fruity', 'bottle', 'linen',
   'Inspired by Madawi', 'Elegant and fruity.', 'A sophisticated floral fruity fragrance.',
   'Elegant, Fruity', array['Fruity','Musky','Floral']::text[], 'A soft, fruity, and radiant scent.',
   'Daytime, Special occasions', array['serenity','pearl','memoria']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Peach','Apple Blossom']::text[], array['Pineapple Blossom']::text[], array['Musk','Wild Rose','Patchouli']::text[],
   8, 50, 0, 0,
   25, false, true,
   null, '2026-08-31T14:07:26.441Z'),
  ('legacy', 'legacy', 'SIMAT LEGACY', 'SIMAT LEGACY', 'SIMAT',
   'cat_signature', '', 'SIMAT LEGACY is a triumphant blend of fresh pineapple, birch, and oakmoss.',
   '', 'Chypre Fruity', 'bottle', 'noir',
   'Inspired by Creed Aventus', 'Powerful and iconic.', 'A bold chypre fruity fragrance.',
   'Powerful, Iconic', array['Fruity','Sweet','Leather']::text[], 'A strong, fruity, and smoky aroma.',
   'Signature scent, Office', array['instinct','clarity','nexus']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Pineapple','Bergamot']::text[], array['Birch','Patchouli']::text[], array['Musk','Oakmoss','Ambergris']::text[],
   8, 50, 0, 0,
   70, true, true,
   null, '2026-08-30T14:07:26.441Z'),
  ('apex', 'apex', 'SIMAT APEX', 'SIMAT APEX', 'SIMAT',
   'cat_signature', '', 'SIMAT APEX is a potent, sweet blend of vanilla, amber, and deep woods.',
   '', 'Amber Woody', 'bottle', 'noir',
   'Inspired by Invictus Elixir', 'Strong and sweet.', 'An intense amber woody fragrance.',
   'Strong, Sweet', array['Vanilla','Amber','Sweet']::text[], 'A powerful, sweet, and victorious scent.',
   'Night out, Clubbing', array['ascend','magnet','poise']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Lavender','Cardamom']::text[], array['Incense','Patchouli']::text[], array['Vanilla Bean','Tonka Bean']::text[],
   8, 50, 0, 0,
   23, false, true,
   null, '2026-08-29T14:07:26.441Z'),
  ('magnet', 'magnet', 'SIMAT MAGNET', 'SIMAT MAGNET', 'SIMAT',
   'cat_signature', '', 'SIMAT MAGNET is an irresistible, party-ready blend of pear, mint, and black vanilla.',
   '', 'Amber Fougere', 'bottle', 'noir',
   'Inspired by Ultra Male', 'Seductive and vibrant.', 'A sweet amber fougere fragrance.',
   'Seductive, Vibrant', array['Sweet','Vanilla','Fruity']::text[], 'A sweet, fruity, and magnetic aroma.',
   'Night out, Parties', array['provocateur','poise','ascend']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Pear','Lavender','Mint']::text[], array['Cinnamon','Clary Sage']::text[], array['Black Vanilla Husk','Amber']::text[],
   8, 50, 0, 0,
   22, false, true,
   null, '2026-08-28T14:07:26.441Z'),
  ('obsidian', 'obsidian', 'SIMAT OBSIDIAN', 'SIMAT OBSIDIAN', 'SIMAT',
   'cat_signature', '', 'SIMAT OBSIDIAN is a sleek, dark blend of aromatic lavender, spices, and deep woods.',
   '', 'Woody Spicy', 'bottle', 'noir',
   'Inspired by Black Lexus', 'Dark and aromatic.', 'A modern woody spicy fragrance.',
   'Dark, Modern', array['Woody','Aromatic','Fresh']::text[], 'A cool, dark, and sophisticated scent.',
   'Evening, Signature scent', array['shadow','temper','vector']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Citrus','Lavender']::text[], array['Spices','Woods']::text[], array['Musk','Amber']::text[],
   8, 50, 0, 0,
   21, false, true,
   null, '2026-08-27T14:07:26.441Z'),
  ('poise', 'poise', 'SIMAT POISE', 'SIMAT POISE', 'SIMAT',
   'cat_signature', '', 'SIMAT POISE is a luxurious, glowing blend of honey, vanilla, and tonka bean.',
   '', 'Amber Fougere', 'bottle', 'noir',
   'Inspired by Le Male Elixir', 'Golden and sweet.', 'A rich amber fougere fragrance.',
   'Golden, Sweet', array['Vanilla','Sweet','Honey']::text[], 'A warm, honeyed, and radiant aroma.',
   'Night out, Winter', array['magnet','attach','ascend']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Lavender','Mint']::text[], array['Vanilla','Benzoin']::text[], array['Honey','Tobacco','Tonka Bean']::text[],
   8, 50, 0, 0,
   20, false, true,
   null, '2026-08-26T14:07:26.441Z'),
  ('vector', 'vector', 'SIMAT VECTOR', 'SIMAT VECTOR', 'SIMAT',
   'cat_signature', '', 'SIMAT VECTOR is a bold, contrasting blend of sweet orange blossom, fruits, and teak wood.',
   '', 'Amber Woody', 'bottle', 'noir',
   'Inspired by Silver Scent', 'Sharp and fruity.', 'A unique amber woody fragrance.',
   'Sharp, Bold', array['Fruity','White Floral','Sweet']::text[], 'A sweet, sharp, and projecting scent.',
   'Night out, Casual', array['magnet','provocateur','obsidian']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Orange Blossom','Lemon']::text[], array['Lavender','Nutmeg']::text[], array['Tonka Bean','Teak Wood']::text[],
   8, 50, 0, 0,
   19, false, true,
   null, '2026-08-25T14:07:26.441Z'),
  ('ignite', 'ignite', 'SIMAT IGNITE', 'SIMAT IGNITE', 'SIMAT',
   'cat_signature', '', 'SIMAT IGNITE is an explosive, tropical blend of juicy mango, ginger, and warm amber.',
   '', 'Amber Woody', 'bottle', 'velvet',
   'Inspired by God of Fire', 'Vibrant and exotic.', 'A fiery amber woody fragrance.',
   'Vibrant, Exotic', array['Mango','Fruity','Sweet']::text[], 'A juicy, fiery, and unique aroma.',
   'Summer nights, Special events', array['pulse','serenity','flow']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Mango','Lemon','Ginger']::text[], array['Woodsy Notes','Jasmine']::text[], array['Amber','Musk','Cypriol Oil']::text[],
   8, 50, 0, 0,
   18, false, true,
   null, '2026-08-24T14:07:26.441Z'),
  ('rebel', 'rebel', 'SIMAT REBEL', 'SIMAT REBEL', 'SIMAT',
   'cat_signature', '', 'SIMAT REBEL is an uncompromising blend of spices, oud, and rich woods.',
   '', 'Woody Spicy', 'bottle', 'noir',
   'Inspired by Al Thaer', 'Bold and spicy.', 'A daring woody spicy fragrance.',
   'Bold, Daring', array['Woody','Spicy','Oriental']::text[], 'A strong, spicy, and rebellious scent.',
   'Evening, Winter', array['temper','impulse','shadow']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Bergamot','Spices']::text[], array['Oud','Floral Notes']::text[], array['Amber','Musk','Sandalwood']::text[],
   8, 50, 0, 0,
   17, false, true,
   null, '2026-08-23T14:07:26.441Z'),
  ('nexus', 'nexus', 'SIMAT NEXUS', 'SIMAT NEXUS', 'SIMAT',
   'cat_signature', '', 'SIMAT NEXUS is a masterful, powdery blend of lavender, rosewood, and premium oud.',
   '', 'Amber Woody', 'bottle', 'velvet',
   'Inspired by Alexandria 2', 'Regal and powdery.', 'A luxurious amber woody fragrance.',
   'Regal, Luxurious', array['Woody','Powdery','Oud']::text[], 'A soft, powdery, and majestic aroma.',
   'Special occasions, Signature scent', array['imprint','sovereign','obsession']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Lavender','Palisander Rosewood']::text[], array['Lily-of-the-Valley','Rose']::text[], array['Agarwood (Oud)','Sandalwood']::text[],
   8, 50, 0, 0,
   16, false, true,
   null, '2026-08-22T14:07:26.441Z'),
  ('desire', 'desire', 'SIMAT DESIRE', 'SIMAT DESIRE', 'SIMAT',
   'cat_signature', '', 'SIMAT DESIRE is a romantic, sweet blend of apple, rose, and vanilla.',
   '', 'Amber Woody', 'bottle', 'noir',
   'Inspired by Dunhill Desire', 'Passionate and sweet.', 'A vibrant amber woody fragrance.',
   'Passionate, Vibrant', array['Fruity','Vanilla','Sweet']::text[], 'A sweet, fruity, and romantic scent.',
   'Date night, Casual', array['vector','magnet','attach']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Apple','Lemon','Neroli']::text[], array['Rose','Teak Wood','Patchouli']::text[], array['Vanilla','Musk']::text[],
   8, 50, 0, 0,
   15, false, true,
   null, '2026-08-21T14:07:26.441Z'),
  ('tobacco', 'tobacco', 'SIMAT TOBACCO', 'SIMAT TOBACCO', 'SIMAT',
   'cat_signature', '', 'SIMAT TOBACCO is a classic, masculine blend of plum, tobacco leaves, and woods.',
   '', 'Aromatic Fruity', 'bottle', 'noir',
   'Inspired by Cigar', 'Classic and earthy.', 'A traditional aromatic fruity fragrance.',
   'Classic, Earthy', array['Tobacco','Fruity','Sweet']::text[], 'A warm, earthy, and nostalgic aroma.',
   'Everyday, Casual', array['nostalgia','sovereign','imperium']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Plum','Pineapple','Pear']::text[], array['Tobacco','Bay Leaf','Marigold']::text[], array['Patchouli','Sandalwood']::text[],
   8, 50, 0, 0,
   14, false, true,
   null, '2026-08-20T14:07:26.441Z'),
  ('umbra', 'umbra', 'SIMAT UMBRA', 'SIMAT UMBRA', 'SIMAT',
   'cat_signature', '', 'SIMAT UMBRA is a deep, mysterious blend of warm spices, smoke, and rich oud.',
   '', 'Amber Woody', 'bottle', 'velvet',
   'Inspired by Oud Black', 'Dark and smoky.', 'An intense amber woody fragrance.',
   'Dark, Mysterious', array['Oud','Warm Spicy','Smoky']::text[], 'A dark, smoky, and enveloping scent.',
   'Evening, Winter', array['shadow','dark-matter','regal']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Spices','Saffron']::text[], array['Rose','Woods']::text[], array['Oud','Amber','Musk']::text[],
   8, 50, 0, 0,
   13, false, true,
   null, '2026-08-19T14:07:26.441Z'),
  ('regal', 'regal', 'SIMAT REGAL', 'SIMAT REGAL', 'SIMAT',
   'cat_signature', '', 'SIMAT REGAL is a captivating contrast of smoky burning wood and sweet vanilla sugar.',
   '', 'Amber Woody', 'bottle', 'velvet',
   'Inspired by Ameer Al Oudh', 'Smoky and sweet.', 'A luxurious amber woody fragrance.',
   'Smoky, Sweet', array['Woody','Vanilla','Smoky']::text[], 'A warm, smoky, and sweet aroma.',
   'Evening, Winter', array['umbra','shadow','imperium']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Woodsy Notes','Agarwood']::text[], array['Sugar','Vanilla']::text[], array['Agarwood (Oud)','Sandalwood']::text[],
   8, 50, 0, 0,
   12, false, true,
   null, '2026-08-18T14:07:26.441Z'),
  ('sanctum', 'sanctum', 'SIMAT SANCTUM', 'SIMAT SANCTUM', 'SIMAT',
   'cat_signature', '', 'SIMAT SANCTUM is a pure, ethereal blend of white flowers, clean musk, and soft woods.',
   '', 'Floral Woody Musk', 'bottle', 'velvet',
   'Inspired by Misk Al Haram', 'Clean and pure.', 'A delicate floral woody musk fragrance.',
   'Clean, Pure', array['Musky','Floral','Clean']::text[], 'A soft, clean, and comforting scent.',
   'Everyday, Office', array['psyche','soften','pearl']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Citrus','Aldehydes']::text[], array['White Flowers','Rose']::text[], array['White Musk','Sandalwood']::text[],
   8, 50, 0, 0,
   11, false, true,
   null, '2026-08-17T14:07:26.441Z'),
  ('imperium', 'imperium', 'SIMAT IMPERIUM', 'SIMAT IMPERIUM', 'SIMAT',
   'cat_signature', '', 'SIMAT IMPERIUM is a masterful, glowing blend of rich resins, amber, and spices.',
   '', 'Amber', 'bottle', 'velvet',
   'Inspired by Ambre Sultan', 'Rich and balsamic.', 'An opulent amber fragrance.',
   'Rich, Opulent', array['Amber','Warm Spicy','Balsamic']::text[], 'A warm, glowing, and majestic aroma.',
   'Evening, Special occasions', array['soma','nostalgia','regal']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Resins','Amber']::text[], array['Bay Leaf','Coriander']::text[], array['Myrrh','Sandalwood','Vanilla']::text[],
   8, 50, 0, 0,
   10, false, true,
   null, '2026-08-16T14:07:26.441Z'),
  ('mood', 'mood', 'SIMAT MOOD', 'SIMAT MOOD', 'SIMAT',
   'cat_signature', '', 'SIMAT MOOD is a deep, sweet blend of rose petals, caramel, and warm oud.',
   '', 'Amber', 'bottle', 'velvet',
   'Inspired by Oud Mood', 'Sweet and rosy.', 'A romantic amber fragrance.',
   'Romantic, Sweet', array['Oud','Rose','Caramel']::text[], 'A sweet, rosy, and woody scent.',
   'Date night, Evening', array['obsession','resonance','comfort']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Rose','Saffron']::text[], array['Patchouli','Caramel']::text[], array['Vanilla','Amber','Oud']::text[],
   8, 50, 0, 0,
   9, false, true,
   null, '2026-08-15T14:07:26.441Z'),
  ('resonance', 'resonance', 'SIMAT RESONANCE', 'SIMAT RESONANCE', 'SIMAT',
   'cat_signature', '', 'SIMAT RESONANCE is an opulent pairing of dark rose, sweet praline, and deep oud wood.',
   '', 'Amber Woody', 'bottle', 'velvet',
   'Inspired by Oud Bouquet Alt', 'Decadent and rich.', 'A luxurious amber woody fragrance.',
   'Decadent, Luxurious', array['Oud','Rose','Vanilla']::text[], 'A sweet, rosy, and woody masterpiece.',
   'Evening, Special occasions', array['obsession','mood','soma']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Saffron']::text[], array['Rose']::text[], array['Agarwood (Oud)','Praline']::text[],
   8, 50, 0, 0,
   8, false, true,
   null, '2026-08-14T14:07:26.441Z'),
  ('feral', 'feral', 'SIMAT FERAL', 'SIMAT FERAL', 'SIMAT',
   'cat_signature', '', 'SIMAT FERAL is an ultra-concentrated, spicy blend of nutmeg, cinnamon, and lavender.',
   '', 'Aromatic', 'bottle', 'noir',
   'Inspired by Sauvage Elixir', 'Intense and spicy.', 'A powerful aromatic fragrance.',
   'Intense, Powerful', array['Warm Spicy','Fresh Spicy']::text[], 'A sharp, spicy, and commanding aroma.',
   'Night out, Signature scent', array['instinct','impulse','clarity']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'men', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Nutmeg','Cinnamon','Cardamom']::text[], array['Lavender']::text[], array['Sandalwood','Licorice','Amber']::text[],
   8, 50, 0, 0,
   7, false, true,
   null, '2026-08-13T14:07:26.441Z'),
  ('noesis', 'noesis', 'SIMAT NOESIS', 'SIMAT NOESIS', 'SIMAT',
   'cat_signature', '', 'SIMAT NOESIS is a captivating, skin-like blend of exotic florals, amber, and musk.',
   '', 'Amber Floral', 'bottle', 'velvet',
   'Inspired by Rosendo Mateu 5', 'Sensual and musky.', 'An elegant amber floral fragrance.',
   'Sensual, Elegant', array['Amber','Vanilla','Musky']::text[], 'A soft, musky, and highly sensual scent.',
   'Date night, Signature scent', array['imprint','sanctum','aura']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Spices','Exotic Floral Notes']::text[], array['Carnation','Lily-of-the-Valley']::text[], array['Amber','Vanilla','Musk']::text[],
   8, 50, 0, 0,
   6, false, true,
   null, '2026-08-12T14:07:26.441Z'),
  ('cloud', 'cloud', 'SIMAT CLOUD', 'SIMAT CLOUD', 'SIMAT',
   'cat_signature', '', 'SIMAT CLOUD is a fluffy, sweet cloud of marshmallow, vanilla, and soft orange blossom.',
   '', 'Floral Fruity Gourmand', 'bottle', 'linen',
   'Inspired by Kayali Marshmallow', 'Dreamy and sweet.', 'A delightful floral fruity gourmand fragrance.',
   'Dreamy, Sweet', array['Sweet','Vanilla','Powdery']::text[], 'A soft, sweet, and comforting aroma.',
   'Everyday, Casual', array['reverie','euphoria','spark']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Marshmallow']::text[], array['Vanilla','Orange Blossom']::text[], array['Musk']::text[],
   8, 50, 0, 0,
   75, true, true,
   null, '2026-08-11T14:07:26.441Z'),
  ('spark', 'spark', 'SIMAT SPARK', 'SIMAT SPARK', 'SIMAT',
   'cat_signature', '', 'SIMAT SPARK is a mouth-watering, crisp blend of red apple, lychee, and berries.',
   '', 'Floral Fruity', 'bottle', 'linen',
   'Inspired by Kayali Eden Apple', 'Juicy and vibrant.', 'A fresh floral fruity fragrance.',
   'Juicy, Vibrant', array['Fruity','Sweet','Fresh']::text[], 'A crisp, fruity, and refreshing scent.',
   'Daytime, Spring/Summer', array['serenity','cloud','memoria']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Red Apple','Lychee']::text[], array['Wild Berries','Raspberry']::text[], array['Vanilla Flower','Musk']::text[],
   8, 50, 0, 0,
   4, false, true,
   null, '2026-08-10T14:07:26.441Z'),
  ('pearl', 'pearl', 'SIMAT PEARL', 'SIMAT PEARL', 'SIMAT',
   'cat_signature', '', 'SIMAT PEARL is a radiant, clean blend of white rose, crisp apple, and soft musk.',
   '', 'Floral Fruity', 'bottle', 'linen',
   'Inspired by Akoya Qissah', 'Luminous and fresh.', 'An elegant floral fruity fragrance.',
   'Luminous, Elegant', array['Floral','Fresh','Musky']::text[], 'A clean, bright, and elegant aroma.',
   'Office, Everyday', array['psyche','soften','sanctum']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'women', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['Citrus','Apple']::text[], array['Rose','Jasmine']::text[], array['Musk','Amber']::text[],
   8, 50, 0, 0,
   3, false, true,
   null, '2026-08-09T14:07:26.441Z'),
  ('aureate', 'aureate', 'SIMAT AUREATE', 'SIMAT AUREATE', 'SIMAT',
   'cat_signature', '', 'SIMAT AUREATE is a warm, beachy blend of sweet coconut, white flowers, and vanilla.',
   '', 'Floral Fruity Gourmand', 'bottle', 'velvet',
   'Inspired by Turab Al Dhahab', 'Tropical and golden.', 'A sunny floral fruity gourmand fragrance.',
   'Tropical, Sunny', array['Sweet','Coconut','Vanilla']::text[], 'A sweet, tropical, and radiant scent.',
   'Summer, Vacations', array['pulse','aura','reverie']::text[],
   '[{"size_ml":40,"price":450},{"size_ml":60,"price":600},{"size_ml":100,"price":850}]'::jsonb,
   null,
   600, null,
   60, 'unisex', 'edp',
   array[]::text[], array[]::text[], array[]::text[],
   array['White Flowers']::text[], array['Coconut','Vanilla']::text[], array['Musk']::text[],
   8, 50, 0, 0,
   2, false, true,
   null, '2026-08-08T14:07:26.441Z'),
  ('discovery-set', 'discovery-set', 'طقم عينات سِمة (5 × 2 مل)', 'SIMAT Discovery Set (5 × 2ml)', 'SIMAT',
   'cat_discovery', 'جرب 5 من أكتر عطورنا المحبوبة على جلدك في البيت. ومع العلبة كارت خصم بقيمة 650 ج.م تخصمه من تمن أي زجاجة تطلبها بعدين.', 'Try five of our most loved perfumes at home on your own skin. Inside the box you will find a 650 EGP voucher you can deduct from any full bottle later.',
   'طقم عينات', 'Discovery Coffret', 'set', 'noir',
   '5 × 2ml', 'Try before you decide.', 'Five 2ml vials of our best sellers.',
   '', array[]::text[], '',
   '', array[]::text[],
   '[]'::jsonb,
   null,
   650, null,
   10, 'unisex', 'edp',
   array['NOCTURNE','IMPRINT','CLARITY','INSTINCT','SOMA']::text[], array[]::text[], array[]::text[],
   array['NOCTURNE','IMPRINT','CLARITY','INSTINCT','SOMA']::text[], array[]::text[], array[]::text[],
   8, 120, 0, 0,
   50, false, true,
   null, '2026-07-07T14:07:26.441Z')
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, name_en = excluded.name_en,
  brand = excluded.brand, category_id = excluded.category_id,
  description = excluded.description, description_en = excluded.description_en,
  family = excluded.family, family_en = excluded.family_en,
  kind = excluded.kind, label_style = excluded.label_style,
  secondary_line = excluded.secondary_line, tagline_en = excluded.tagline_en,
  short_description_en = excluded.short_description_en,
  scent_character_en = excluded.scent_character_en, accords_en = excluded.accords_en,
  wear_profile_en = excluded.wear_profile_en, occasion_en = excluded.occasion_en,
  related = excluded.related, variants = excluded.variants,
  top_notes_en = excluded.top_notes_en, heart_notes_en = excluded.heart_notes_en,
  base_notes_en = excluded.base_notes_en, price = excluded.price,
  old_price = excluded.old_price, size_ml = excluded.size_ml,
  gender = excluded.gender, concentration = excluded.concentration,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes,
  base_notes = excluded.base_notes, longevity_hours = excluded.longevity_hours,
  is_featured = excluded.is_featured, is_active = excluded.is_active,
  image_url = coalesce(excluded.image_url, products.image_url),
  image_hover_url = coalesce(excluded.image_hover_url, products.image_hover_url);

-- الكوبونات
insert into public.coupons
  (code, type, value, min_order, max_discount, expires_at,
   usage_limit, used_count, is_active) values
  ('SIMAT10', 'percent', 10, 0, null, '2027-10-05T14:07:26.441Z', 0, 0, true),
  ('ALEXANDRIA', 'percent', 10, 0, null, '2027-10-05T14:07:26.441Z', 0, 0, true),
  ('SIMAT15', 'percent', 15, 3000, null, '2027-10-05T14:07:26.441Z', 0, 0, true)
on conflict (code) do nothing;

-- إخفاء كتالوج العرض القديم (قبل تصميم الـ Prototype) لو كان متزرع.
-- المنتجات اللي الأدمن ضافها بنفسه مش بتتأثر.
update public.products set is_active = false where id in (
  'p_001','p_002','p_003','p_004','p_005','p_006','p_007','p_008','p_009','p_010',
  'p_011','p_012','p_013','p_014','p_015','p_016','p_017','p_018','p_019','p_020',
  'simat-bordeaux','simat-noir','simat-ivoire','royal-velvet');
update public.categories set is_active = false where id in (
  'cat_oriental','cat_french','cat_oud','cat_niche','cat_body','cat_gift');
